name: martiandao_aptos_web3
description: Web3 SDK For Aptos
version: 1.0.0

environment:
  sdk: '>=2.16.2 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.5
dependencies: 
  bip39: ^1.0.6
  hex: ^0.2.0
  http: ^0.13.4
  pinenacl: ^0.3.3
  sha3: ^0.2.0
